spring.application.name=gateway

server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

spring.cloud.gateway.server.webflux.routes[0].id=catalogue-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://catalogue-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/produits/**


spring.cloud.gateway.server.webflux.routes[1].id=clients-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://clients-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/clients/**

spring.cloud.gateway.server.webflux.routes[2].id=commandes-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://commandes-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/commandes/**
